/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // 可以自动根据目录生成，也可以自己配置，建议自己配置
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  HtmlSidebar: [
    {
      type: 'category',
      label: 'HTML和CSS',
      items: [
        {
          type: 'doc',
          label: 'HTML和CSS',
          id: 'HtmlSidebar/静态页面布局基础',
        },
        // {
        //   type: 'link',
        //   label: '个人博客',
        //   href: 'https://blog.csdn.net/Shen_zhihao',
        // },
      ],
    },
  ],
  JavaScriptSidebar: [
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        {
          type: 'doc',
          label: 'JavaScript从基础到高级',
          id: 'JavaScriptSidebar/JavaScript从基础到高级',
        },
        {
          type: 'doc',
          label: 'ECMAScript6',
          id: 'JavaScriptSidebar/ECMAScript6',
        },
        {
          type: 'doc',
          label: '数组、字符串、对象的方法',
          id: 'JavaScriptSidebar/数组、字符串、对象的方法',
        },
        {
          type: 'doc',
          label: '常用函数、ES新特性',
          id: 'JavaScriptSidebar/常用函数、ES新特性',
        },
        {
          type: 'doc',
          label: 'Typescript基础',
          id: 'JavaScriptSidebar/Typescript基础',
        },
      ],
    },
  ],
  ReactSidebar: [
    {
      type: 'category',
      label: 'React',
      items: [
        {
          type: 'doc',
          label: 'React 基础',
          id: 'ReactSidebar/React 基础',
        },
        {
          type: 'doc',
          label: 'ReactHooks',
          id: 'ReactSidebar/ReactHooks',
        },
        {
          type: 'doc',
          label: '实用的自定义Hooks',
          id: 'ReactSidebar/实用的自定义Hooks',
        },
        {
          type: 'doc',
          label: 'React历代更新',
          id: 'ReactSidebar/React历代更新',
        },
      ],
    }
  ],
  NodeSidebar: [
    {
      type: 'category',
      label: 'NodeJs',
      items: [
        {
          type: 'doc',
          label: 'NodeJs基础',
          id: 'NodeSidebar/NodeJs基础',
        },
      ],
    }
  ],
  WorkSidebar: [
    {
      type: 'category',
      label: '前端工程化',
      items: [
        {
          type: 'doc',
          label: 'Git命令和npm包管理',
          id: 'WorkSidebar/Git命令和npm包管理',
        },
        {
          type: 'doc',
          label: 'gulp工具',
          id: 'WorkSidebar/gulp工具',
        },
        {
          type: 'doc',
          label: 'Webpack专题',
          id: 'WorkSidebar/Webpack专题',
        },
        {
          type: 'doc',
          label: 'React项目构建',
          id: 'WorkSidebar/React项目构建',
        },
        {
          type: 'doc',
          label: '项目安装TypeScript和配置',
          id: 'WorkSidebar/项目安装TypeScript和配置',
        },
      ],
    },
  ],
  ComponentsSidebar: [
    {
      type: 'category',
      label: '组件库相关配置',
      items: [
        {
          type: 'doc',
          label: 'axios实例相关',
          id: 'ComponentsSidebar/axios实例相关',
        },
        {
          type: 'doc',
          label: 'Echarts相关配置',
          id: 'ComponentsSidebar/Echarts相关配置',
        },
      ],
    },
  ],
};

module.exports = sidebars;
